/**
 * Account form field configuration by account type
 */

export type { FieldConfig } from '@views/AccountHub/accountTypeFieldConfigTypes';
import type { FieldConfig } from '@views/AccountHub/accountTypeFieldConfigTypes';

export const ACCOUNT_TYPE_FIELD_CONFIG: Record<string, FieldConfig> = {
  'Current Account': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Savings Account': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Premium Bonds': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Fixed / Bonus Rate Saver': {
    showInterestRate: true,
    showFixedBonusRate: true,
    showFixedBonusRateEndDate: true,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Fixed Rate ISA': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: true,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Cash ISA': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Stocks ISA': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'ISA': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Deferred DC Pension': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: true,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Deferred DB Pension': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: true,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: true,
    showAssetClass: true,
  },
  'Deferred Cash': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: true,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Deferred Shares': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: true,
    showNumberOfShares: true,
    showUnderlying: true,
    showPrice: true,
    showPurchasePrice: true,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'RSU': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: true,
    showNumberOfShares: true,
    showUnderlying: true,
    showPrice: true,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Trust Bank Account': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'Trust Stocks Investment Account': {
    showInterestRate: false,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
  'DEFAULT': {
    showInterestRate: true,
    showFixedBonusRate: false,
    showFixedBonusRateEndDate: false,
    isDeferredType: false,
    showNumberOfShares: false,
    showUnderlying: false,
    showPrice: false,
    showPurchasePrice: false,
    showPensionMonthlyPayment: false,
    showAssetClass: true,
  },
};
