"""Add feature tables: Account, Institution, AccountAttribute, AccountEvent, InstitutionSecurityCredentials

Revision ID: de3af94e70a5
Revises: 002
Create Date: 2026-02-04 12:58:37.682688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3af94e70a5'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_id'), 'institutions', ['id'], unique=False)
    op.create_index(op.f('ix_institutions_userid'), 'institutions', ['userid'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('institutionid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('statusid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institutionid'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['statusid'], ['reference_data.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['reference_data.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_userid'), 'accounts', ['userid'], unique=False)
    op.create_table('institution_security_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('institutionid', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=True),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['institutionid'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['reference_data.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_security_credentials_id'), 'institution_security_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_institution_security_credentials_institutionid'), 'institution_security_credentials', ['institutionid'], unique=False)
    op.create_index(op.f('ix_institution_security_credentials_userid'), 'institution_security_credentials', ['userid'], unique=False)
    op.create_table('account_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['reference_data.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_attributes_accountid'), 'account_attributes', ['accountid'], unique=False)
    op.create_index(op.f('ix_account_attributes_id'), 'account_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_account_attributes_userid'), 'account_attributes', ['userid'], unique=False)
    op.create_table('account_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('accountid', sa.Integer(), nullable=False),
    sa.Column('typeid', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['typeid'], ['reference_data.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_events_accountid'), 'account_events', ['accountid'], unique=False)
    op.create_index(op.f('ix_account_events_id'), 'account_events', ['id'], unique=False)
    op.create_index(op.f('ix_account_events_userid'), 'account_events', ['userid'], unique=False)
    op.drop_constraint('user_profile_emailaddress_key', 'user_profile', type_='unique')
    op.drop_index('ix_user_profile_emailaddress', table_name='user_profile')
    op.create_index(op.f('ix_user_profile_emailaddress'), 'user_profile', ['emailaddress'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_user_profile_emailaddress'), table_name='user_profile')
    op.create_index('ix_user_profile_emailaddress', 'user_profile', ['emailaddress'], unique=False)
    op.create_unique_constraint('user_profile_emailaddress_key', 'user_profile', ['emailaddress'])
    op.drop_index(op.f('ix_account_events_userid'), table_name='account_events')
    op.drop_index(op.f('ix_account_events_id'), table_name='account_events')
    op.drop_index(op.f('ix_account_events_accountid'), table_name='account_events')
    op.drop_table('account_events')
    op.drop_index(op.f('ix_account_attributes_userid'), table_name='account_attributes')
    op.drop_index(op.f('ix_account_attributes_id'), table_name='account_attributes')
    op.drop_index(op.f('ix_account_attributes_accountid'), table_name='account_attributes')
    op.drop_table('account_attributes')
    op.drop_index(op.f('ix_institution_security_credentials_userid'), table_name='institution_security_credentials')
    op.drop_index(op.f('ix_institution_security_credentials_institutionid'), table_name='institution_security_credentials')
    op.drop_index(op.f('ix_institution_security_credentials_id'), table_name='institution_security_credentials')
    op.drop_table('institution_security_credentials')
    op.drop_index(op.f('ix_accounts_userid'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_institutions_userid'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_id'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
